### ISSUE TITLE
Trace all functions in a module

### ISSUE THREAD

**Issue by andytill** [andytill/erlyberly#10]
Enable the star icon for modules in the module tree. When a module is "traced" all functions in the module are traced, un-tracing a module will remove all traces from functions in the module.

**Comment by ruanpienaar** [comment]
Guess this can be closed now :+1:

**Comment by andytill** [comment]
It can! Thanks for the contribution, I have made a new release with the change. I like how it puts a trace on all the functions displayed when a filter is set rather than all the functions in the module.

I have also added your name to a list of contributors, hope that is ok. I can merge a PR on the README if you want to remove it or change the formatting etc.

**Comment by ruanpienaar** [comment]
I see, i didn't notice that!
I guess the Java loops over the getChildren method. 
Could possibly be called "Trace All", or something.
Cool Stuff, i'll help out.
