### ISSUE TITLE
Regression: Not yet returned long running calls are not distinguished with yellow background

### ISSUE THREAD

**Issue by aboroska** [andytill/erlyberly#103]
Traced functions which neither crashed nor returned are normally coloured yellow in the trace window. This is not working currently. To reproduce in Elixir you can try the following module:
```
defmodule TestYellow do
  def sloooow ms do
    Process.sleep ms
  end
end
```
In the iex shell:
```
iex(1)> c "testyellow.ex"
iex(2)> TestYellow.sloooow 10_000
```

Or in Erlang:
```
-module(testyellow).
-export([sloooow/1]).
sloooow(Ms) ->
    timer:sleep(Ms).
```
erl shell after setting the traces for sloooow and get_all_env:
```
spawn(testyellow, sloooow, [60000]), application:get_all_env(). 
```
 _get_all_env_ is traced and shown, but the trace line displaying _sloooow_ is not yellow while the function is executing.

**Comment by andytill** [comment]
Fixed in #104.
