### ISSUE TITLE
Module list - Right click - disable tracing

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#107]
It would be using to disable all modules being traced on the Modules list right click menu, or maybe a menu button.

**Comment by andytill** [comment]
You can put `#t` in the modules filter to show all traces, then `ctrl+shift+t` to toggle the traces off, does that help?

**Comment by ruanpienaar** [comment]
That does work for me. But in the essence of pure laziness, wouldn't a big red button be easier ? :)

**Comment by aboroska** [comment]
+1 for the panic/pause button. When the gui is stressed by flood of traces maybe even a single click can be difficult enough to manage. "Pause traces"?

**Comment by andytill** [comment]
We need a pause/play button for rate limiting but it wouldn't remove all the traces.

**Comment by andytill** [comment]
Suspend/Unsuspend tracing button, it doesn't remove traces though. https://github.com/andytill/erlyberly/pull/111

**Comment by ruanpienaar** [comment]
I've tested it, it works as expected. 
When you're tracing something like ets:lookup, and it get's noisy, 
you have to ability to then suspend, and on the remote node, i can 
see the load average drop. Nice one :+1:

**Comment by andytill** [comment]
@ruanpienaar thanks for testing. Is tracing consuming significant amount of resources?  If so, could you do a quick eprof on it when the load is high and see where time is being spent?

**Comment by andytill** [comment]
@ruanpienaar on second thoughts I don't know if that will be possible because eprof uses tracing to profile.

**Comment by ruanpienaar** [comment]
I traced ets:lookup/2 on the EB Gui, and noticed a cpu utilization change from 11% to c. 40%.
after i hit suspend, it took about 1-2 seconds, and the cpu utilization was back to 11%. that's the minimal testing i went through :)

**Comment by andytill** [comment]
Thanks for testing @ruanpienaar. Going to close this now that the suspend button is merged.
