### ISSUE TITLE
OS X - 'Nameserver not responding on ...'

### ISSUE THREAD

**Issue by jordan0day** [andytill/erlyberly#108]
I'm on OS X Yosemite and having an issue connecting to a node I'm running locally. I can connect the nodes using net_adm:ping, but erlyberly complains with "Nameserver not responding on Jordans-MacBook-Pro.trea..."

<img width="512" alt="screen shot 2016-05-11 at 10 45 24 am" src="https://cloud.githubusercontent.com/assets/545037/15187155/9ba953a8-1765-11e6-8dcc-2edee01dba6f.png">

```bash
$ erl -name test -setcookie test_cookie
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.2.1  (abort with ^G)
(test@Jordans-MacBook-Pro.trea.local)1>

...


$ erl -name test2 -setcookie test_cookie
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.2.1  (abort with ^G)
(test2@Jordans-MacBook-Pro.trea.local)1> net_adm:ping('test@Jordans-MacBook-Pro.trea.local').
pong
```

As per the troubleshooting section in the README, I've verified that epmd is running:
```bash
$ ps aux | grep epmd
jordan           9581   0.0  0.0  2497076    468   ??  S     2May16   0:01.23 /usr/local/Cellar/erlang/18.2.1/lib/erlang/erts-7.2.1/bin/epmd -daemon
```

I'm guessing this is probably something configured wrong on my system or domain or something, but I'm really not sure what I should look at next, troubleshooting-wise?

**Comment by andytill** [comment]
According to the comment below the java erlang driver does not allow full stops in the node name. Could you try with a node name without the full stop?

https://github.com/erlide/erlide/issues/158#issuecomment-35062967

**Comment by jordan0day** [comment]
Yes, it works if I have a nodename without any period in it.

It also works for a node name with an IP (like test@127.0.0.1), but, interestingly, when I start my node with 

```bash
erl -name test2@Jordans-MacBook-Pro.local -setcookie test_cookie
```

So it's not *necessarily* the presence of a period that causes the issue. This makes me think it is most likely some kind of issue with my local network/os x's hostname configuration stuff.

**Comment by andytill** [comment]
Great, I have updated the trouble shooting section with this issue.
