### ISSUE TITLE
Publish to Hex.pm

### ISSUE THREAD

**Issue by brucify** [andytill/erlyberly#113]
Hex.pm is the package manager for the Erlang ecosystem. Uploading to Hex.pm would allow people to more easily discover this project.

https://hex.pm/packages?search=tracing

Use Rebar3 to publish. See publishing guide on http://www.rebar3.org/docs/publishing-packages

**Comment by andytill** [comment]
@brucify I don't think this is even possible, and I don't want a rebar3 dependency, sorry.
