### ISSUE TITLE
Connect to epmd on a non standard port

### ISSUE THREAD

**Issue by andreausu** [andytill/erlyberly#118]
Hi,

since we're using docker in production we're exposing multiple applications on the same server on different ports, and then we're launching erl like this in order to use run observer on localhost while connecting to the remote application:

```
ERL_EPMD_PORT=40001 erl -sname debug@hostname -setcookie cookiename -hidden -run observer
```

Is there a way to pass the custom epmd port to erlyberly?

Cheers,
Andrea

**Comment by andytill** [comment]
Hi @andreausu 

I haven't tried it before but it looks like the port can be set using the same environment variable `ERL_EPMD_PORT`.

https://github.com/andytill/jinterface/blob/e561017fc01975da28555e50d35c11ef2f256ec3/src/main/java/com/ericsson/otp/erlang/OtpEpmd.java#L58

**Comment by andreausu** [comment]
I don't know why I didn't think of trying it before, it works like a charm, thank you!
