### ISSUE TITLE
Unable to install on OSX

### ISSUE THREAD

**Issue by stringerbell** [andytill/erlyberly#123]
I'm running: 
- OSX 10.11.16 (Capitan)
- Java 1.8.0_102
- Erlang 19.0.2
- Elixir 1.3.2

and ran into a build problem on the `./mvnw clean compile install assembly:single && java -jar target/*runnable.jar` step.

The error looked like this:
`...Unsupported major.minor version 51.0...`

I was eventually able to figure it out, and I'm happy to make a PR to update the docs, but a missing step in the installation steps for OSX is make sure you have 

`export JAVA_HOME=/Library/Java/JavaVirtualMachines/#{your_jdk_version}.jdk/Contents/Home`

where `#{your_jdk_version}` is correct. (mine is `jdk1.8.0_102`)

somewhere. (mine is in `~/.bash_profile`)

**Comment by andytill** [comment]
Thanks for persevering. That looks like java 1.7 may have been on your path.

It would be great if you could update the docs. There is a wiki page for installing java https://github.com/andytill/erlyberly/wiki/Java-install which should be linked off the README (no PR necessary just go ahead and edit it :)), or it could be added to the README if you think the wiki is not visible enough.

**Comment by andytill** [comment]
@ruanpienaar another case of java version mismatch, are you up for adding that maven plugin for version checking and testing that it catches this case?

**Comment by ruanpienaar** [comment]
@andytill 
I'll have a look :+1:

**Comment by stringerbell** [comment]
Sorry for the delay. Done!
