### ISSUE TITLE
Show local AND global registered names in the process pane

### ISSUE THREAD

**Issue by andytill** [andytill/erlyberly#135]
Current behaviour implemented in #133, if a process is globally registered but not locally, then the global name is shown in the process pane, otherwise the local name overrides.

If a process is locally and globally registered then both should be shown. For example:

```
my_local_srv (my_global_srv)
```

This should be enough to differentiate global and local names, anyone using global should recognise the bracketed process name, and the brackets are not shown for non-local processes. The global and local registered names should be sent as separate props in the proplist. Both props are optional. Putting style on part of the text is not so simple in JavaFX I think, so just using text is best.

**Comment by maruks** [comment]
I sent you PR

**Comment by andytill** [comment]
Fixed in https://github.com/andytill/erlyberly/pull/139
