### ISSUE TITLE
Bitstrings not formatted

### ISSUE THREAD

**Issue by andytill** [andytill/erlyberly#136]
Erlyberly does not show the value of bitstrings, all it shows is the java type information.

To reproduce, trace on `io:format/1` and run the following in the shell:

```erlang
io:format("~p", [<<2:7>>]).
<<2:7>>
```
Now view the trace in erlyberly.

**Comment by ruanpienaar** [comment]
yeah
Output:
```
"~p", [#Bin<1-1>]
```

**Comment by ruanpienaar** [comment]
Found this: http://erlang.org/doc/apps/jinterface/java/com/ericsson/otp/erlang/OtpErlangBitstr.html
Trying to make a quick fix...

**Comment by ruanpienaar** [comment]
Seems to arrive in TraceManager.java as : 
```java
{call,[{pid,"<0.69.0>"},{reg_name,undefined},{fn,{io,format,["~p",[#Bin<1-1>]]}},{timetamp_call_us,1484415818143206},{stack_trace,[{erl_eval,do_apply,6},{shell,exprs,7},{shell,eval_exprs,7},{shell,eval_loop,3}]}]}
```

**Comment by ruanpienaar** [comment]
played around with erlyberly.erl
The bitstring survives the correct format, when made into a binary string.
Trying a alternative solution of formatting it in ErlangFormatter.java

**Comment by andytill** [comment]
Thanks for taking a look @ruanpienaar 😄
