### ISSUE TITLE
Trace all module functions

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#16]
I see that currently when you press Ctrl + t on a module name, or right click trace on a module name then it won't trace it.

Would it make sense to create "Trace all Functions" in the right click menu of a module ?

**Comment by andytill** [comment]
Yeah, that would be awesome.

The feature is captured in #10 but if you are willing to give this a go I can close that as a duplicate.

**Comment by ruanpienaar** [comment]
ok - i'll try and get a PR out.

**Comment by ruanpienaar** [comment]
Closing this as it's a duplicate to #10. Will complete the required work, and references to #10.

**Comment by andytill** [comment]
Ok, let me know if you have any problems.
