### ISSUE TITLE
Display source code of function/modules

### ISSUE THREAD

**Issue by horvand** [andytill/erlyberly#20]
If a module was compiled with `debug_info`, it should be easy to show the source code for a function or the whole module by pretty-printing the appropriate portion of the abstract code.
It would be a nice little feature to have.

**Comment by andytill** [comment]
Hi Andras! That would be useful.

The source attribute in a module's module_info could be used if it exists to give actual source, but I can't think of a good way to find it in a release, even though source is often shipped.

**Comment by horvand** [comment]
I coded the Erlang bit, check https://gist.github.com/horvand/e9638a5c644ef0d56c72
@ruanpienaar agreed to help with the Java part.

**Comment by ruanpienaar** [comment]
i'll get it done

**Comment by ruanpienaar** [comment]
Here's the commit : https://github.com/ruanpienaar/erlyberly/commit/a58bf50fff3c833a8fb6c21325e8a606246cd8a7

Will make a PR later

![erly](https://cloud.githubusercontent.com/assets/584394/7654937/62ff5b66-fb18-11e4-9f81-74727bf04078.png)

**Comment by ruanpienaar** [comment]
Obviously have to check/test Elixir, i guess...

**Comment by andytill** [comment]
Don't worry about elixir, I don't know enough about the elixir syntax parser to maintain it anyway.

It is fine to have caveats like erlang code only as long as they are documented e.g. View Code (erlang only) in the menu item for obviousness and in the README.

Also could you make the font mono spaced, and use the string value so the speech marks at the beginning are not visible?

Will test further over the weekend. Looking great :+1:

**Comment by ruanpienaar** [comment]
Will do, made the mistake of using a windows git gui, fixing some commits :)

**Comment by ruanpienaar** [comment]
Also, wanted to ask, 
What Erlang version should i compile, the erlyberly.beam ?

**Comment by andytill** [comment]
I am using 17.4, I'll recompile when I merge.

**Comment by ruanpienaar** [comment]
Cool thanks.

**Comment by andytill** [comment]
Could you please also provide a menu item that displays the formatted AST? Something like `io_lib:format("~p", [abstract_code(Module)])` and display the string as it is in the screenshot. It is very useful to check if values are being transformed into constants.

**Comment by ruanpienaar** [comment]
Will do :+1:

**Comment by ruanpienaar** [comment]
Hey @andytill , made a commit : https://github.com/ruanpienaar/erlyberly/tree/view_code

Still have to:

1) prettyfy the font
2) add some padding from the border, so it's easily readible.
3) add "View Abstract Code"

I guess it would be great, if you'd take a glance at the changes, and please review it.

**Comment by ruanpienaar** [comment]
Made a [PR](https://github.com/andytill/erlyberly/pull/26)

**Comment by andytill** [comment]
I have merged this in, excellent stuff. Thanks guys!
