### ISSUE TITLE
FInd a way to recompile the erlyberly.erl

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#27]
When you rebuild the project. Could be a nice-to-have.

**Comment by andytill** [comment]
That would be nice, it looks like there are some Maven plugins to do this but it would need to be cross platform.

I am just using an eclipse external tool run configuration at the moment.

**Comment by ruanpienaar** [comment]
I've found [this](http://erlang-plugin.sourceforge.net/).
We could potentially write some unit tests if needed too.
IE [compile](http://lindenbaum.github.io/maven-erlang-plugin/2.2.0/compile-mojo.html)

**Comment by andytill** [comment]
Looks interesting, out of the box eunit support is a benefit over the maven plugins to execute arbitrary commands I had looked at before.

**Comment by andytill** [comment]
Added the `exec-maven-plugin` plugin to the pom file to execute erlc when `mvn compile` is run.
