### ISSUE TITLE
Function icons are confusing when highlighted [GUI confusion]

### ISSUE THREAD

**Issue by gordonguthrie** [andytill/erlyberly#33]
The reversing of the GUI colours is well confusing - the highlight makes it seem that the selection is unselected

<img width="331" alt="screen shot 2015-08-05 at 10 40 20" src="https://cloud.githubusercontent.com/assets/125496/9082829/6fdb62b8-3b5e-11e5-95f9-fbefc22b2242.png">

**Comment by andytill** [comment]
Now you mentioned it, this is really bothering me as well.

How about this? It uses the share icons from FontAwesome.

![erlyberly-export-icons](https://cloud.githubusercontent.com/assets/213455/9095227/fcd68234-3bad-11e5-8d41-cac0c1a0e80f.png)

**Comment by gordonguthrie** [comment]
Perfecto on the selection.

Do you need to mark both the exported and non-exported functions - you could choose to mark one as private (with a padlock) and the other unmarked, or one as exported - even by just boldening the function name...

**Comment by andytill** [comment]
Padlocks look better, I still like having the icon there, personal preference maybe.

![erlyberly-export-icons](https://cloud.githubusercontent.com/assets/213455/9099265/46db2f24-3bc7-11e5-8f60-ceaa442917bd.png)

**Comment by andytill** [comment]
Released in 0.6.4.
