### ISSUE TITLE
CSS error message on startup [Error message]

### ISSUE THREAD

**Issue by gordonguthrie** [andytill/erlyberly#34]
![screen shot 2015-08-06 at 10 52 00](https://cloud.githubusercontent.com/assets/125496/9108888/3377d952-3c29-11e5-9408-34cfd88cba77.png)

This error message is dumped to console on startup

**Comment by andytill** [comment]
I believe it is fixed in the newer versions of FontAwesome but the new API is incompatible with the one erlyberly uses.  Hardly insurmountable but still more than a version bump.

**Comment by ruanpienaar** [comment]
Tried using the latest/newer versions of (FontAwesome)[https://bitbucket.org/Jerady/fontawesomefx]. It seems there was a re-write and it's usage changed from 8.0.10 onwards.
