### ISSUE TITLE
Not all modules appear in the module list

### ISSUE THREAD

**Issue by gordonguthrie** [andytill/erlyberly#35]
Tried to add a trace to riak_kv_index_fsm but it didn't appear on the modules list
<img width="341" alt="screen shot 2015-08-11 at 11 13 50" src="https://cloud.githubusercontent.com/assets/125496/9195352/1ab7e0d4-401a-11e5-8033-0efec50166af.png">

**Comment by andytill** [comment]
Are you sure it was loaded at the time?  A dev rel will not load a module until a function on it has been called.

If it happens again try pressing `ctrl+r` to load all modules.
