### ISSUE TITLE
JavaFX Application Thread exception on startup

### ISSUE THREAD

**Issue by tgrk** [andytill/erlyberly#39]
I was not able to start application using `java -jar erlyberly-0-6-6-runnable.jar` command.

Full startup output:
---
http://pastebin.com/S0dqddNg

Java version
---
```bash
4 Downloads $ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
```

Ubuntu version
---
```bash
5 Downloads $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by andytill** [comment]
It turns out that you 1.8.0_05 is not enough, `Stage#setAlwaysOnTop` was added in 8u20, you will need to install the latest JDK.

The doc for the method are here:

https://docs.oracle.com/javase/8/javafx/api/javafx/stage/Stage.html#setAlwaysOnTop-boolean-

**Comment by andytill** [comment]
Fixed the required java version in the README.
