### ISSUE TITLE
Pattern matching broken for code reloads [Elixir Tracing - bit noisy]

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#42]
Once Erlyberly is connected and tracing any function, then iex shell becomes noisy with printouts
when you hit Enter or Tab:

skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347092}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347120}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347187}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347235}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347260}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347284}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347311}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347340}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347364}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347392}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347416}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347438}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347462}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347489}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347516}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347563}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347588}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347612}}
skipped trace_ts {trace_ts,<0.32.0>,call,
                           {code,ensure_loaded,
                                 ['Elixir.String.Chars.Integer']},
                           {1443,109505,347635}}

**Also with a massive gem like this :**

iex(alchemy@ipap629)17> skipped trace_ts {trace_ts,<0.32.0>,call,
skipped trace_ts {trace_ts,<0.26.0>,call,
                           {code,get_chunk,
                                 [<<70,79,82,49,0,0,85,220,66,69,65,77,69,120,
                                    68,99,0,0,17,104,131,104,2,100,0,14,101,
                                    108,105,120,105,114,95,100,111,99,115,95,
                                    118,49,108,0,0,0,3,104,2,100,0,4,100,111,
                                    99,115,108,0,0,0,12,104,5,104,2,100,0,13,
                                    95,95,98,101,104,97,118,105,111,117,114,95,
                                    95,97,1,97,31,100,0,3,100,101,102,108,0,0,
                                    0,1,104,3,100,0,4,97,116,111,109,106,100,0,
                                    6,69,108,105,120,105,114,106,100,0,5,102,
                                    97,108,115,101,104,5,104,2,100,0,10,101,
                                    120,99,101,112,116,105,111,110,63,97,1,97,
                                    39,100,0,3,100,101,102,108,0,0,0,1,104,3,
                                    100,0,4,116,101,114,109,106,100,0,3,110,
                                    105,108,106,109,0,0,0,52,82,101,116,117,
                                    114,110,115,32,96,116,114,117,101,96,32,
                                    105,102,32,116,104,101,32,103,105,118,101,
                                    110,32,96,116,101,114,109,96,32,105,115,32,
                                    97,110,32,101,120,99,101,112,116,105,111,
                                    110,46,10,104,5,104,2,100,0,6,102,111,114,
                                    109,97,116,97,3,97,142,100,0,3,100,101,102,
                                    108,0,0,0,3,104,3,100,0,4,107,105,110,100,
                                    106,100,0,3,110,105,108,104,3,100,0,7,112,
                                    97,121,108,111,97,100,106,100,0,3,110,105,
                                    108,104,3,100,0,2,92,92,106,108,0,0,0,2,
                                    104,3,100,0,10,115,116,97,99,107,116,114,
                                    97,99,101,106,100,0,3,110,105,108,100,0,3,
                                    110,105,108,106,106,109,0,0,1,9,78,111,114,
                                    109,97,108,105,122,101,115,32,97,110,100,
                                    32,102,111,114,109,97,116,115,32,116,104,
                                    114,111,119,47,101,114,114,111,114,115,47,
                                    101,120,105,116,115,32,97,110,100,32,115,
                                    116,97,99,107,116,114,97,99,101,46,10,10,
                                    73,116,32,114,101,108,105,101,115,32,111,
                                    110,32,96,102,111,114,109,97,116,95,98,97,
                                    110,110,101,114,47,51,96,32,97,110,100,32,
                                    96,102,111,114,109,97,116,95,115,116,97,99,
                                    107,116,114,97,99,101,47,49,96,10,116,111,
                                    32,103,101,110,101,114,97,116,101,32,116,
                                    104,101,32,102,105,110,97,108,32,102,111,
                                    114,109,97,116,46,10,10,78,111,116,101,32,
                                    116,104,97,116,32,96,123,58,69,88,73,84,44,
                                    32,112,105,100,125,96,32,100,111,32,110,
                                    111,116,32,103,101,110,101,114,97,116,101,
                                    32,97,32,115,116,97,99,107,116,114,97,99,
                                    101,32,116,104,111,117,103,104,10,40,97,
                                    115,32,116,104,101,121,32,97,114,101,32,
                                    114,101,116,114,105,101,118,101,100,32,97,
                                    115,32,109,101,115,115,97,103,101,115,32,
                                    119,105,116,104,111,117,116,32,115,116,97,
                                    99,107,116,114,97,99,101,115,41,46,10,104,
                                    5,104,2,100,0,13,102,111,114,109,97,116,95,
                                    98,97,110,110,101,114,97,3,97,111,100,0,3,
                                    100,101,102,108,0,0,0,3,104,3,100,0,4,107,
                                    105,110,100,106,100,0,3,110,105,108,104,3,
                                    100,0,9,101,120,99,101,112,116,105,111,110,
                                    106,100,0,3,110,105,108,104,3,100,0,2,92,
                                    92,106,108,0,0,0,2,104,3,100,0,10,115,116,
                                    97,99,107,116,114,97,99,101,106,100,0,3,
                                    110,105,108,100,0,3,110,105,108,106,106,
                                    109,0,0,1,207,78,111,114,109,97,108,105,
                                    122,101,115,32,97,110,100,32,102,111,114,
                                    109,97,116,115,32,97,110,121,32,116,104,
                                    114,111,119,44,32,101,114,114,111,114,32,
                                    97,110,100,32,101,120,105,116,46,10,10,84,
                                    104,101,32,109,101,115,115,97,103,101,32,
                                    105,115,32,102,111,114,109,97,116,116,101,
                                    100,32,97,110,100,32,100,105,115,112,108,
                                    97,121,101,100,32,105,110,32,116,104,101,
                                    32,115,97,109,101,10,102,111,114,109,97,
                                    116,32,97,115,32,117,115,101,100,32,98,121,

**Comment by andytill** [comment]
Ah this is a major annoyance, thanks.  I think this is also happening in erlang.

When a module is loaded in the VM. erlyberly monitors code loads to reapply traces to reloaded modules, but I broke it when I added timestamps because it is looking for `{trace, ....}` or something like that! Haven't debugged it thoroughly.

**Comment by andytill** [comment]
Fixed in release 0.6.7

**Comment by ruanpienaar** [comment]
Awesome! - i'll spread the word!

**Comment by andytill** [comment]
How was erlyberly doing on elixir, any other problems?

**Comment by ruanpienaar** [comment]
I'll test it! 1 sec

**Comment by ruanpienaar** [comment]
Fixed in Elixir.
No more noise :musical_note:

**Comment by andytill** [comment]
:+1:
