### ISSUE TITLE
Sort Order of messages

### ISSUE THREAD

**Issue by gordonguthrie** [andytill/erlyberly#44]
You attach some trace flags on functions and then do some actions on the system under test

You set some traces and get a range of trace messages which represent the sequence of events in the system

You then sort by duration, args, modules, functions etc, etc

There is then no way to resort them into the original sequence

**Comment by andytill** [comment]
Sounds like #41 Trace logs cannot be put in order once sorted on column,

This was fixed in the last release, 0.6.7.
