### ISSUE TITLE
Display Connected node on GUI

### ISSUE THREAD

**Issue by ruanpienaar** [andytill/erlyberly#66]
It would be useful if the erlyberly GUI has a space in which the currently connected erlang/elixir node name is shown.

**Comment by andytill** [comment]
:+1: This is annoying me as well.

I was thinking of changing the window title to something like `erlyberly-7676 connected to dev1@127.0.0.1` or something similar. The erlyberly node name should be shorter as well to make it readable, the last four or five chars of the UUID it is currently using should do.

**Comment by andytill** [comment]
Fixed in PR #73
