### ISSUE TITLE
Exported function called privately is not traced

### ISSUE THREAD

**Issue by andytill** [andytill/erlyberly#69]
If a function is exported from a given module but called within the module, the trace will not be shown in erlyberly.

**Comment by ruanpienaar** [comment]
Could that be because of the dbg trace match spec, that doesn't match on local function calls? Just a guess :) 
I can have a quick look later

**Comment by andytill** [comment]
Cool, something to do with this case statement most likely but I haven't had time to check it out https://github.com/andytill/erlyberly/blob/master/src/main/resources/erlyberly/beam/erlyberly.erl#L189
