### ISSUE TITLE
Regression: module_info/0, module_info/1 spam

### ISSUE THREAD

**Issue by aboroska** [andytill/erlyberly#88]
The module_info calls are spamming the traces again.

To reproduce click on "Exported Function Trace" on any module.
![screen shot 2016-04-03 at 16 52 37](https://cloud.githubusercontent.com/assets/1858479/14233302/8aaf7bfc-f9bc-11e5-970e-908f9524b2af.png)

**Comment by ruanpienaar** [comment]
I wrote [this](https://github.com/andytill/erlyberly/blob/b521f88db3c3486b4a56add9ade7b2cdc6aaba5d/src/main/java/erlyberly/ModFunc.java#L141) for Recursive Trace.

**Comment by andytill** [comment]
Fixed.
